[env]
TARGET_ABI = { value = 'aarch64-linux-android', condition = { env_not_set = [ 'TARGET_ABI' ] }}
TARGET_SDK = '31'
DEPLOY_PATH = '/data/local/tmp/${CARGO_MAKE_PROJECT_NAME}'
ADB = 'adb'

[tasks.default]
alias = 'build'

[tasks.prepare]
script = '''
rm -rf .cargo

mkdir -p .cargo

cat << EOF > .cargo/config.toml
[build]
target = "$TARGET_ABI"

[target.$TARGET_ABI]
ar = "$(ls "$ANDROID_NDK"/toolchains/llvm/prebuilt/*/bin/llvm-ar | head -n 1)"
linker = "$(ls -r "$ANDROID_NDK"/toolchains/llvm/prebuilt/*/bin/"$TARGET_ABI"*-clang | head -n 1)"
EOF
'''

[tasks.build]
dependencies = [ 'prepare' ]
command = 'cargo'
args = [ 'build' ]

[tasks.release]
dependencies = [ 'prepare' ]
command = 'cargo'
args = [ 'build', '--release' ]

[tasks.upx-release]
dependencies = [ 'release' ]
command = 'upx'
args = [ './target/${TARGET_ABI}/release/${CARGO_MAKE_PROJECT_NAME}' ]

