[env]
TARGET_ABI = 'aarch64-linux-android'
ANDROID_SDK_ROOT = '${HOME}/Android/Sdk'
NDK_VERSION = '23'

[tasks.run]
dependencies = ['install']
command = 'adb'
args = ['shell', 'su', '-c', '/data/local/tmp/${CARGO_MAKE_PROJECT_NAME}', '${@}']

[tasks.install]
dependencies = ['build']
script = 'adb push target/${TARGET_ABI}/release/${CARGO_MAKE_PROJECT_NAME} /data/local/tmp/'

[tasks.build]
dependencies = ['config']
command = 'cargo'
args = ['build', '--target', '${TARGET_ABI}', '--release']

[tasks.config]
script = '''
echo "[build]" > .cargo/config
echo "target = \"${TARGET_ABI}\"" >> .cargo/config
echo >> .cargo/config
echo "[target.${TARGET_ABI}]" >> .cargo/config
echo "linker = \"$(ls -r ${ANDROID_SDK_ROOT}/ndk/${NDK_VERSION}*/toolchains/llvm/prebuilt/*/bin/${TARGET_ABI}*-clang | head -n 1)\"" >> .cargo/config
'''
